#!/bin/sh
# Inner, network-disabled S19k Pro Buildroot producer.
#
# This script is executed only by s19k_hermetic_image_producer.py inside the
# inspected digest-pinned OCI boundary.  It consumes read-only source,
# dependency and public release-input mounts; every generated byte goes
# to a build-specific mutable mount.  It never contacts a miner or writes NAND.

set -eu
umask 022

fail() {
    echo "S19K_HERMETIC_INNER_REFUSED: $*" >&2
    exit 1
}

require_env() {
    case "$1" in
        ''|*[!A-Z0-9_]*) fail "unsafe environment variable name" ;;
    esac
    eval "value=\${$1:-}"
    [ -n "$value" ] || fail "missing required environment: $1"
    case "$value" in
        *"
"*|*""*) fail "unsafe control character in environment: $1" ;;
    esac
}

for name in \
    SOURCE_DATE_EPOCH \
    DCENT_SOURCE_COMMIT \
    DCENT_SOURCE_COMMIT_EPOCH \
    DCENT_BUILD_TARGET \
    DCENT_BUILD_ARCH \
    DCENT_TOOLCHAIN_ID \
    DCENT_MANIFEST_PUBLIC_KEY_HEX \
    DCENT_RELEASE_PUBKEY_FILE \
    DCENT_S19K_UNSIGNED_INTERMEDIATE \
    DCENT_S19K_EXPECTED_RELEASE_KEY_SHA256 \
    DCENT_S19K_NATIVE_OWNER_RECEIPT \
    DCENT_S19K_STOCK_RECOVERY_RECEIPT \
    DCENT_PROVENANCE_SOURCE_SNAPSHOT \
    DCENT_HERMETIC_BUILD_ID \
    DCENT_HERMETIC_BUILD_ROOT_ID \
    DCENT_HERMETIC_BUILDER_IMAGE \
    DCENT_HERMETIC_DEPENDENCY_BUNDLE_ID \
    DCENT_HERMETIC_RELEASE_INPUT_ID \
    DCENT_HERMETIC_EXPECTED_PACKAGE
do
    require_env "$name"
done

[ "$SOURCE_DATE_EPOCH" = "$DCENT_SOURCE_COMMIT_EPOCH" ] ||
    fail "source epochs disagree"
case "$SOURCE_DATE_EPOCH" in
    ''|*[!0-9]*) fail "SOURCE_DATE_EPOCH is not an unsigned integer" ;;
esac
[ "$SOURCE_DATE_EPOCH" -le 4294967295 ] ||
    fail "SOURCE_DATE_EPOCH exceeds the uImage timestamp range"
case "$DCENT_SOURCE_COMMIT" in
    *[!0-9a-f]*|'') fail "source commit is not lowercase hex" ;;
esac
[ "${#DCENT_SOURCE_COMMIT}" -eq 40 ] || [ "${#DCENT_SOURCE_COMMIT}" -eq 64 ] ||
    fail "source commit is not a full object ID"
[ "$DCENT_BUILD_TARGET" = dcentos_am3_s19kpro_defconfig ] ||
    fail "unexpected Buildroot target"
[ "$DCENT_BUILD_ARCH" = aarch64 ] || fail "unexpected build architecture"
[ "$DCENT_S19K_UNSIGNED_INTERMEDIATE" = 1 ] ||
    fail "A/B build requires exact unsigned-intermediate profile"
[ -z "${DCENT_RELEASE_SIGNING_KEY:-}" ] ||
    fail "A/B build received forbidden private signing-key environment"
case "$DCENT_MANIFEST_PUBLIC_KEY_HEX" in
    *[!0-9a-f]*|'') fail "manifest public key is not lowercase hex" ;;
esac
[ "${#DCENT_MANIFEST_PUBLIC_KEY_HEX}" -eq 64 ] ||
    fail "manifest public key must be 32 raw bytes"

SOURCE_STAGE=/dcent/source-snapshot
SOURCE_TREE=$SOURCE_STAGE/tree
SOURCE_DESCRIPTOR=$SOURCE_STAGE/snapshot.json
DEPENDENCY_STAGE=/dcent/dependencies
DEPENDENCY_INPUTS=$DEPENDENCY_STAGE/inputs
RELEASE_INPUT_STAGE=/dcent/release-inputs
SOURCE_WORK=/dcent/work/source
CARGO_HOME=/dcent/work/cargo-home
CARGO_TARGET_DIR=/dcent/work/cargo-target
BUILDROOT_OUTPUT=/dcent/work/buildroot-output
DASHBOARD_WORK=/dcent/work/dashboard
RESULT_ROOT=/dcent/work/result
TMPDIR=/dcent/work/tmp
PROJECT=$SOURCE_WORK/DCENT_OS_Antminer
BUILDROOT_SOURCE_ARCHIVE=$DEPENDENCY_INPUTS/buildroot/source/buildroot-source.tar
BUILDROOT_SOURCE=$SOURCE_WORK/buildroot-upstream
BUILDROOT_DL=$DEPENDENCY_INPUTS/buildroot/dl
CARGO_VENDOR=$DEPENDENCY_INPUTS/cargo/vendor
DASHBOARD_NPM_CACHE=$DEPENDENCY_INPUTS/dashboard/npm-cache
AML_INPUT_ROOT=$DEPENDENCY_INPUTS/amlogic/s19kpro
PRODUCER=$SOURCE_TREE/DCENT_OS_Antminer/scripts/s19k_hermetic_image_producer.py
SNAPSHOT_HELPER=$SOURCE_TREE/DCENT_OS_Antminer/scripts/source_snapshot.py

for directory in \
    "$SOURCE_TREE" \
    "$DEPENDENCY_INPUTS" \
    "$RELEASE_INPUT_STAGE" \
    "$SOURCE_WORK" \
    "$CARGO_HOME" \
    "$CARGO_TARGET_DIR" \
    "$BUILDROOT_OUTPUT" \
    "$DASHBOARD_WORK" \
    "$RESULT_ROOT" \
    "$TMPDIR" \
    "$BUILDROOT_DL" \
    "$CARGO_VENDOR" \
    "$DASHBOARD_NPM_CACHE" \
    "$AML_INPUT_ROOT"
do
    [ -d "$directory" ] && [ ! -L "$directory" ] ||
        fail "required non-link directory is absent: $directory"
done
for file in \
    "$SOURCE_DESCRIPTOR" \
    "$PRODUCER" \
    "$SNAPSHOT_HELPER" \
    "$BUILDROOT_SOURCE_ARCHIVE" \
    "$DCENT_RELEASE_PUBKEY_FILE" \
    "$DCENT_S19K_NATIVE_OWNER_RECEIPT" \
    "$DCENT_S19K_STOCK_RECOVERY_RECEIPT" \
    "$AML_INPUT_ROOT/vmlinux.bin" \
    "$AML_INPUT_ROOT/devicetree.dtb" \
    "$AML_INPUT_ROOT/fw-info"
do
    [ -f "$file" ] && [ ! -L "$file" ] ||
        fail "required regular non-link input is absent: $file"
done

for directory in \
    "$SOURCE_WORK" \
    "$CARGO_HOME" \
    "$CARGO_TARGET_DIR" \
    "$BUILDROOT_OUTPUT" \
    "$DASHBOARD_WORK" \
    "$RESULT_ROOT" \
    "$TMPDIR"
do
    [ -z "$(find "$directory" -mindepth 1 -maxdepth 1 -print -quit)" ] ||
        fail "mutable build root did not start empty: $directory"
done

command -v python3 >/dev/null 2>&1 || fail "python3 is missing from builder image"
command -v tar >/dev/null 2>&1 || fail "tar is missing from builder image"
command -v make >/dev/null 2>&1 || fail "make is missing from builder image"
command -v cargo >/dev/null 2>&1 || fail "cargo is missing from builder image"
command -v rustc >/dev/null 2>&1 || fail "rustc is missing from builder image"
command -v zig >/dev/null 2>&1 || fail "zig is missing from builder image"
command -v npm >/dev/null 2>&1 || fail "npm is missing from builder image"

python3 "$SNAPSHOT_HELPER" verify \
    --commit "$DCENT_SOURCE_COMMIT" \
    "$DCENT_PROVENANCE_SOURCE_SNAPSHOT" >/dev/null
python3 "$PRODUCER" verify-dependencies \
    --descriptor "$DEPENDENCY_STAGE/bundle.json" \
    --expected-source-commit "$DCENT_SOURCE_COMMIT" \
    --expected-builder-image "$DCENT_HERMETIC_BUILDER_IMAGE" \
    --expected-toolchain-id "$DCENT_TOOLCHAIN_ID" >/dev/null
python3 "$PRODUCER" verify-release-inputs \
    --descriptor "$RELEASE_INPUT_STAGE/release-inputs.json" \
    --expected-release-key-sha256 "$DCENT_S19K_EXPECTED_RELEASE_KEY_SHA256" >/dev/null

echo "=== S19k hermetic offline build ==="
echo "build_id=$DCENT_HERMETIC_BUILD_ID"
echo "build_root_id=$DCENT_HERMETIC_BUILD_ROOT_ID"
echo "source_commit=$DCENT_SOURCE_COMMIT"
echo "source_date_epoch=$SOURCE_DATE_EPOCH"
echo "dependency_bundle_id=$DCENT_HERMETIC_DEPENDENCY_BUNDLE_ID"
echo "release_input_id=$DCENT_HERMETIC_RELEASE_INPUT_ID"
echo "runtime_network_mode=none"
echo "network_used=false"
echo "build_cache_reused=false"
if [ -r /proc/net/dev ]; then
    echo "--- /proc/net/dev (network-none observation) ---"
    sed -n '1,16p' /proc/net/dev
fi

# Copy only authenticated source bytes. Generated dashboard and compiler output
# paths are excluded even if an older signed source commit happened to track a
# convenience artifact in one of those directories.
(cd "$SOURCE_TREE" && tar \
    --exclude='./DCENT_OS_Antminer/dashboard/dist' \
    --exclude='./DCENT_OS_Antminer/dashboard/node_modules' \
    --exclude='./DCENT_OS_Antminer/dcentrald/target' \
    --exclude='./DCENT_OS_Antminer/buildroot' \
    -cf - .) | (cd "$SOURCE_WORK" && tar -xf -)
[ -d "$PROJECT" ] || fail "authenticated source copy lacks DCENT_OS_Antminer"
NORMALIZE_SOURCE=$SOURCE_TREE/DCENT_OS_Antminer/scripts/s19k_hermetic_normalize_source_copy.py
[ -f "$NORMALIZE_SOURCE" ] && [ ! -L "$NORMALIZE_SOURCE" ] ||
    fail "authenticated source lacks mutable-copy normalizer"
python3 "$NORMALIZE_SOURCE" \
    "$SOURCE_TREE" "$SOURCE_WORK" \
    --exclude DCENT_OS_Antminer/dashboard/dist \
    --exclude DCENT_OS_Antminer/dashboard/node_modules \
    --exclude DCENT_OS_Antminer/dcentrald/target \
    --exclude DCENT_OS_Antminer/buildroot >/dev/null

# The sealed dependency stage carries the exact pinned Buildroot Git archive
# as one regular file. Extract it only into this invocation-private source root;
# tracked links are therefore recreated inside the disposable build boundary,
# never in the host-sealed dependency stage.
[ ! -e "$BUILDROOT_SOURCE" ] && [ ! -L "$BUILDROOT_SOURCE" ] ||
    fail "private Buildroot source root already exists"
mkdir "$BUILDROOT_SOURCE"
tar --no-same-owner -xf "$BUILDROOT_SOURCE_ARCHIVE" -C "$BUILDROOT_SOURCE"
[ -f "$BUILDROOT_SOURCE/Makefile" ] && [ ! -L "$BUILDROOT_SOURCE/Makefile" ] ||
    fail "sealed Buildroot Git archive lacks its top-level Makefile"

# Cargo consumes only the read-only vendored source closure. All index, target,
# wrapper, and temporary writes are private to this build root.
mkdir -p "$CARGO_HOME/bin"
cat > "$CARGO_HOME/config.toml" <<EOF
[source.crates-io]
replace-with = "dcentos-hermetic-vendor"

[source.dcentos-hermetic-vendor]
directory = "$CARGO_VENDOR"

[net]
offline = true
EOF
cat > "$CARGO_HOME/bin/zig-cc-aarch64-musl" <<'EOF'
#!/bin/sh
exec zig cc -target aarch64-linux-musl -mcpu=cortex_a53 "$@"
EOF
cat > "$CARGO_HOME/bin/zig-ar" <<'EOF'
#!/bin/sh
exec zig ar "$@"
EOF
chmod 700 "$CARGO_HOME/bin/zig-cc-aarch64-musl" "$CARGO_HOME/bin/zig-ar"
export CARGO_HOME CARGO_TARGET_DIR TMPDIR
export CARGO_NET_OFFLINE=true
export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER="$CARGO_HOME/bin/zig-cc-aarch64-musl"
export CC_aarch64_unknown_linux_musl="$CARGO_HOME/bin/zig-cc-aarch64-musl"
export AR_aarch64_unknown_linux_musl="$CARGO_HOME/bin/zig-ar"
export RUSTFLAGS="-C target-cpu=cortex-a53 -C target-feature=+crt-static --remap-path-prefix=$SOURCE_WORK=/dcent-source --remap-path-prefix=$CARGO_TARGET_DIR=/dcent-build"

echo "--- toolchain identity ---"
rustc -vV
cargo -V
zig version
cargo build \
    --manifest-path "$PROJECT/dcentrald/Cargo.toml" \
    --release \
    --locked \
    --offline \
    --target aarch64-unknown-linux-musl

RUST_RELEASE=$CARGO_TARGET_DIR/aarch64-unknown-linux-musl/release
for binary in dcentrald dcentos-init
do
    [ -f "$RUST_RELEASE/$binary" ] && [ ! -L "$RUST_RELEASE/$binary" ] ||
        fail "Cargo did not produce $binary"
done
PROJECT_RELEASE=$PROJECT/dcentrald/target/aarch64-unknown-linux-musl/release
mkdir -p "$PROJECT_RELEASE"
for binary in dcentrald dcentos-init
do
    [ ! -e "$PROJECT_RELEASE/$binary" ] && [ ! -L "$PROJECT_RELEASE/$binary" ] ||
        fail "source execution stage already contains $binary"
    cp "$RUST_RELEASE/$binary" "$PROJECT_RELEASE/$binary"
done

# Rebuild the dashboard from the authenticated lockfile with a build-private
# copy of the content-addressed npm cache. No tracked dist byte is eligible.
(cd "$PROJECT/dashboard" && tar \
    --exclude='./dist' \
    --exclude='./node_modules' \
    -cf - .) | (cd "$DASHBOARD_WORK" && tar -xf -)
mkdir "$DASHBOARD_WORK/npm-cache"
(cd "$DASHBOARD_NPM_CACHE" && tar -cf - .) |
    (cd "$DASHBOARD_WORK/npm-cache" && tar -xf -)
(cd "$DASHBOARD_WORK" && \
    npm ci --offline --ignore-scripts --cache "$DASHBOARD_WORK/npm-cache" && \
    npm run build)
[ -f "$DASHBOARD_WORK/dist/index.html" ] ||
    fail "fresh dashboard build lacks dist/index.html"
[ ! -e "$PROJECT/dashboard/dist" ] && [ ! -L "$PROJECT/dashboard/dist" ] ||
    fail "source execution stage retained a tracked dashboard dist"
mkdir "$PROJECT/dashboard/dist"
(cd "$DASHBOARD_WORK/dist" && tar -cf - .) |
    (cd "$PROJECT/dashboard/dist" && tar -xf -)

# Buildroot source and downloads remain read-only. All configured/generated
# trees are rooted under this invocation's output mount.
DEFCONFIG=dcentos_am3_s19kpro_defconfig
DEFCONFIG_FULL=dcentos_am3_s19kpro_full_defconfig
CONFIG_DIR=$PROJECT/br2_external_dcentos/configs
FULL_CONFIG=$CONFIG_DIR/$DEFCONFIG_FULL
[ ! -e "$FULL_CONFIG" ] && [ ! -L "$FULL_CONFIG" ] ||
    fail "authenticated source unexpectedly contains generated full defconfig"
{
    echo '# generated hermetically from authenticated fragments'
    cat "$CONFIG_DIR/dcentos-common.fragment"
    cat "$CONFIG_DIR/dcentos_am3_aml_common.fragment"
    cat "$CONFIG_DIR/$DEFCONFIG"
} > "$FULL_CONFIG"

export TARGET=am3-s19kpro
export DCENT_PACKAGE_STATUS=release
export DCENT_RELEASE_IMAGE=1
export DCENT_REQUIRE_RELEASE_KEY=1
export DCENT_S19K_UNSIGNED_INTERMEDIATE=1
export DCENT_REQUIRE_RELEASE_PROVENANCE=1
export DCENT_ALLOW_UNSIGNED_SYSUPGRADE=0
export DCENT_REQUIRE_INSTALLABLE_PACKAGE=1
export DCENT_SOURCE_TREE_STATE=exact_git_object_snapshot
export DCENT_BUILD_TARGET DCENT_BUILD_ARCH DCENT_TOOLCHAIN_ID
export DCENT_RELEASE_CAPSULE_MODE=1
export DCENT_CAPSULE_PROVENANCE_VERIFIED=1
export DCENT_PROVENANCE_HELPER="$PROJECT/scripts/source_snapshot.py"
export DCENT_AM3_AML_KERNEL="$AML_INPUT_ROOT/vmlinux.bin"
export DCENT_AM3_AML_DTB="$AML_INPUT_ROOT/devicetree.dtb"
export DCENT_AM3_AML_FW_INFO="$AML_INPUT_ROOT/fw-info"
export BR2_DL_DIR="$BUILDROOT_DL"

make -C "$BUILDROOT_SOURCE" \
    O="$BUILDROOT_OUTPUT" \
    BR2_EXTERNAL="$PROJECT/br2_external_dcentos" \
    "$DEFCONFIG_FULL"
# Fixed concurrency is part of the hermetic build contract. Host CPU topology
# must not alter scheduling or the bytes retained from A versus B.
BUILD_JOBS=8
make -C "$BUILDROOT_SOURCE" \
    O="$BUILDROOT_OUTPUT" \
    BR2_EXTERNAL="$PROJECT/br2_external_dcentos" \
    BR2_DL_DIR="$BUILDROOT_DL" \
    -j"$BUILD_JOBS"

BUILT_PACKAGE=$BUILDROOT_OUTPUT/images/dcentos-sysupgrade-am3-s19kpro.unsigned.tar
[ -f "$BUILT_PACKAGE" ] && [ ! -L "$BUILT_PACKAGE" ] ||
    fail "Buildroot did not produce the S19k package"
[ "$DCENT_HERMETIC_EXPECTED_PACKAGE" = "$RESULT_ROOT/dcentos-sysupgrade-am3-s19kpro.unsigned.tar" ] ||
    fail "coordinator supplied an unexpected result path"

# Publish the private runtime result exactly once through opened file handles.
python3 - "$BUILT_PACKAGE" "$DCENT_HERMETIC_EXPECTED_PACKAGE" <<'PY'
import hashlib
import os
from pathlib import Path
import stat
import sys

source = Path(sys.argv[1])
destination = Path(sys.argv[2])
metadata = os.lstat(source)
if not stat.S_ISREG(metadata.st_mode) or stat.S_ISLNK(metadata.st_mode):
    raise SystemExit("runtime package is not a regular non-link file")
if metadata.st_nlink != 1:
    raise SystemExit("runtime package has ambiguous hard links")
source_fd = os.open(source, os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0))
destination_fd = None
try:
    opened = os.fstat(source_fd)
    if (opened.st_dev, opened.st_ino, opened.st_size) != (
        metadata.st_dev,
        metadata.st_ino,
        metadata.st_size,
    ):
        raise SystemExit("runtime package changed while opening")
    destination_fd = os.open(
        destination,
        os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0),
        0o600,
    )
    digest = hashlib.sha256()
    size = 0
    while True:
        chunk = os.read(source_fd, 1024 * 1024)
        if not chunk:
            break
        digest.update(chunk)
        size += len(chunk)
        view = memoryview(chunk)
        while view:
            written = os.write(destination_fd, view)
            if written <= 0:
                raise SystemExit("short runtime package write")
            view = view[written:]
    os.fsync(destination_fd)
finally:
    os.close(source_fd)
    if destination_fd is not None:
        os.close(destination_fd)
print(f"runtime_package_sha256={digest.hexdigest()}")
print(f"runtime_package_bytes={size}")
PY

python3 "$SNAPSHOT_HELPER" verify \
    --commit "$DCENT_SOURCE_COMMIT" \
    "$DCENT_PROVENANCE_SOURCE_SNAPSHOT" >/dev/null
python3 "$PRODUCER" verify-dependencies \
    --descriptor "$DEPENDENCY_STAGE/bundle.json" \
    --expected-source-commit "$DCENT_SOURCE_COMMIT" \
    --expected-builder-image "$DCENT_HERMETIC_BUILDER_IMAGE" \
    --expected-toolchain-id "$DCENT_TOOLCHAIN_ID" >/dev/null
python3 "$PRODUCER" verify-release-inputs \
    --descriptor "$RELEASE_INPUT_STAGE/release-inputs.json" \
    --expected-release-key-sha256 "$DCENT_S19K_EXPECTED_RELEASE_KEY_SHA256" >/dev/null

echo "S19K_HERMETIC_INNER_OK"
echo "install_authority_granted=false"
echo "mutation_authority_granted=false"
echo "nand_write_authorized=false"
echo "live_hardware_contacted=false"
echo "private_signing_key_present=false"
